version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: civic_affordability_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: affordability
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/sql
      - ./seeds:/seeds

volumes:
  pgdata:
